source 'http://rubygems.org'

gem 'rails', '3.1.3'
gem 'jquery-rails'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

group :test do
  # Pretty printed test output
  gem 'turn', '~> 0.8.3', :require => false
end

# DEVELOPMENT

group :development do
    gem 'sqlite3'
end

# PRODUCTION

group :production do
    gem 'pg'
    gem 'thin'
end

# ALL

gem 'daemons'
gem 'delayed_job_active_record'
gem 'httparty'

